# Generated by Django 5.0.6 on 2026-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('free', 'آزاد'), ('timed', 'زمان\u200cدار')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('billiard', 'Billiard'), ('snooker', 'Snooker'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('airHocky', 'Air Hocky'), ('system', 'Custom System'), ('tennis', 'Tennis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='extra_controller_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقد'), ('account_debit', 'حساب'), ('account_settlement', 'تسویه')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
